import Head from 'next/head'
import About from '@/components/About'
import Navbar from '@/components/Navbar'
import Contact from '@/components/Contact'
import Experience from '@/components/Experience'
import Skills from '@/components/Skills'
import JobTitle from '@/components/JobTitle'
import styles from "../style/Style.module.css"
import Technologies from '@/components/Technologies'
import Footer from '@/components/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>My portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.background}>
      <Navbar />
      <JobTitle />
      <About />
      <div className={styles.content_container}>     
        <Experience />
        <Skills />
        <Technologies />
        <Footer />
      </div>
      
      </div>
    </>
  )
}
