import Head from 'next/head'
import About from '@/components/About'
import Navbar from '@/components/Navbar'
import Contact, { Button } from '@/components/Contact'
import Experience from '@/components/Experience'
import Skills from '@/components/Skills'
import JobTitle from '@/components/JobTitle'
import styles from "../style/Style.module.css"
import Technologies from '@/components/Technologies'
import Footer from '@/components/Footer'
import Education from '@/components/Education'
import Certificates from '@/components/Certificates'
import Form from '@/components/Form'
import Navbar2 from '@/components/Navbar2'
import { useRef } from 'react'


export default function Home() {
  const refEducation = useRef(null);
  function handleScrollEducation() {
    refEducation.current?.scrollIntoView({
      behavior: 'smooth',
      block: 'nearest',
      inline: 'center'
    });
  }
  return (
    <>
      <Head>
        <title>My portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.background}>
        <div className={styles.page_header}>
          <button onClick={handleScrollEducation}>press</button>
          <Navbar />
          <JobTitle />
          <About />
        </div>
        <div className={styles.skills_education}>
          <Skills />
          <Education ref={refEducation} />
          <Experience />
          <Technologies />   
          <Certificates />
          <Form />
          <Navbar2 />
        </div>
        <Footer />
      </div>
    </>
  )
}
