import Head from 'next/head'
import About from '@/components/About'
import Navbar from '@/components/Navbar'
import Contact, { Button } from '@/components/Contact'
import Experience from '@/components/Experience'
import Skills from '@/components/Skills'
import JobTitle from '@/components/JobTitle'
import styles from "../style/Style.module.css"
import Technologies from '@/components/Technologies'
import Footer from '@/components/Footer'
import Education from '@/components/Education'
import Certificates from '@/components/Certificates'
import Form from '@/components/Form'
import { useRef } from 'react'
import Image from "next/image"
import github from "../images/github.svg"
import linkedin from "../images/linkedin.png"
import TechnologiesDescription from '@/components/TechnologiesDescription'


export default function Home() {
  
  const refEducation = useRef(null);
  function handleScrollEducation() {
    refEducation.current?.scrollIntoView({
      behavior: 'smooth',
      block: 'nearest',
      inline: 'center'
    });
  }
  const refExperience = useRef(null);
  function handleScrollExperience() {
    refExperience.current?.scrollIntoView({
      behavior: 'smooth',
      block: 'nearest',
      inline: 'center'
    });
  }
  const refTechnologies = useRef(null);
  function handleScrollTechnologies() {
    refTechnologies.current?.scrollIntoView({
      behavior: 'smooth',
      block: 'nearest',
      inline: 'center'
    });
  }
  const refSkills = useRef(null);
  function handleScrollSkills() {
    refSkills.current?.scrollIntoView({
      behavior: 'smooth',
      block: 'nearest',
      inline: 'center'
    });
  }
  const refCertificates = useRef(null);
  function handleScrollCertificates() {
    refCertificates.current?.scrollIntoView({
      behavior: 'smooth',
      block: 'nearest',
      inline: 'center'
    });
  }
  const refContact = useRef(null);
  function handleScrollContact() {
    refContact.current?.scrollIntoView({
      behavior: 'smooth',
      block: 'nearest',
      inline: 'center'
    });
  }
  return (
    <>
      <Head>
        <title>My portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.background}>
        <div className={styles.navbar_group}>
          <div className={styles.contact_links}>
            <a href="https://www.linkedin.com/in/diana-dinu-front-end-dev/" target="_blank">
                <Image src={linkedin.src} height={50} width={50} className={styles.linkedin} alt="linkedin image">
                </Image>
            </a>          
            <a href="https://github.com/Diana-Elen" target="_blank">
                <Image src={github.src} height={50} width={50} className={styles.github} alt="github image">
                </Image>
            </a>
          </div>
          <div className={styles.navbar_buttons}>
              <button onClick={handleScrollSkills} className={styles.nav_button}>skills</button>
              <button onClick={handleScrollEducation} className={styles.nav_button}>education</button>
              <button onClick={handleScrollExperience} className={styles.nav_button}>experience</button>
              <button onClick={handleScrollTechnologies} className={styles.nav_button}>technologies</button>
              <button onClick={handleScrollCertificates} className={styles.nav_button}>certificates</button>
              <button onClick={handleScrollContact} className={styles.nav_button}>contact</button>  
          </div>
        </div>
        <div className={styles.skills_education}>
          <JobTitle />
          <About />
          <Skills ref={refSkills}/>
          <Education ref={refEducation} />
          <Experience ref={refExperience}/>
          <Technologies ref={refTechnologies}/>   
          <Certificates ref={refCertificates}/>
          <Form ref={refContact}/>
        </div>
        <TechnologiesDescription />
      
        <Footer />
      </div>
    </>
  )
}
